### ISSUE TITLE
initial translations

### ISSUE THREAD

**Issue by schmar00** [GeoEra-GIP/WP4-Semantics#1]
languages: de, es, si

**Comment by schmar00** [comment]
translation into German language finished and online (v1.1)

**Comment by schmar00** [comment]
translation Spanish and Slovenian language finished and online (v1.1)

**Comment by auretepereira** [comment]
translation to Portuguese is foreseen?

**Comment by schmar00** [comment]
yes, of course

**Comment by schmar00** [comment]
translation of keywords in Portuguese language is in progress and will be available at new location in European Geoscience Registry at https://data.geoscience.earth/ncl/geoera/keyword as soon as possible
