### ISSUE TITLE
URI design, final decision

### ISSUE THREAD

**Issue by schmar00** [GeoEra-GIP/WP4-Semantics#5]

**Comment by HorChr** [comment]
Here I leave my comment

**Comment by schmar00** [comment]
the transfer of the **geoscience.earth** domain to EGS is now in place, so we can start to use it

**Comment by schmar00** [comment]
new URIs according to new EGS domain name:
All keyword concepts have got new identifiers based on the new domain name "data.geoscience.earth" registered by EGS. URI patterns are adapted to the naming conventions of geoscience.earth host. E.g. for the keyword hazard the URI was changed from previous testing environment http://resource.geolba.ac.at/geoera_keyword/hazard to https://data.geoscience.earth/ncl/geoera/keyword/1358. The previous URIs remain in the Keyword Thesaurus to query with property "http://purl.org/dc/terms/replaces".
