### ISSUE TITLE
communicate parallel projects

### ISSUE THREAD

**Issue by schmar00** [GeoEra-GIP/WP4-Semantics#7]

**Comment by nmtoken** [comment]
Not sure if the 'parallel' term here is meant to be for other GeoEra activities, or other vocabulary activities, such as that of the IUGS CGI Terminology Working group ~

http://www.cgi-iugs.org/tech_collaboration/geoscience_terminology_working_group.html

**Comment by schmar00** [comment]
This issue, or rather the goal of this task, is to inform parallel projects (on the topic of keyword thesaurus and multilingual semantic search) about the status of GeoERA. Or to incorporate important findings from these parallel projects.
