### ISSUE TITLE
Link GeoEra concepts to IUGS-CGI terms where possible

### ISSUE THREAD

**Issue by nmtoken** [GeoEra-GIP/WP4-Semantics#8]
I'm not sure why GeoERA is creating it's own vocabulary where one already exists, (possibly not all terms exist), but please make linkages from the GeoERA vocab to the IUGS-CGI wherever possible.

Just looking at pp_project_geoerakeywords.concepts.rdf we have for example:

    <rdf:Description rdf:about="http://resource.geolba.ac.at/geoera_keyword/rhyolite">
	<rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>
	<prefLabel xmlns="http://www.w3.org/2004/02/skos/core#" xml:lang="en">rhyolite</prefLabel>
    </rdf:Description>

Which should be linked to:  http://resource.geosciml.org/classifier/cgi/lithology/rhyolite

    <rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:dcterms="http://purl.org/dc/terms/"
    xmlns:skos="http://www.w3.org/2004/02/skos/core#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
    xmlns:api="http://purl.org/linked-data/api/vocab#"
    xmlns:foaf="http://xmlns.com/foaf/0.1/">
      <rdf:Description rdf:about="http://resource.geosciml.org/classifier/cgi/lithology">
        <skos:member>
          <rdfs:Resource rdf:about="http://resource.geosciml.org/classifier/cgi/lithology/rhyolite">
            <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>
            <dcterms:source xml:lang="en">LeMaitre et al. 2002</dcterms:source>
            <skos:broader>
              <rdf:Description rdf:about="http://resource.geosciml.org/classifier/cgi/lithology/rhyolitoid">
                <skos:narrower rdf:resource="http://resource.geosciml.org/classifier/cgi/lithology/rhyolite"/>
              </rdf:Description>
            </skos:broader>
            <skos:definition xml:lang="en">rhyolitoid in which the ratio of plagioclase to total feldspar is between 0.1 and 0.65.</skos:definition>
            <skos:inScheme rdf:resource="http://resource.geosciml.org/classifierscheme/cgi/2016.01/simplelithology"/>
            <skos:prefLabel xml:lang="en">rhyolite</skos:prefLabel>
            <skos:example xml:lang="en">rhyodacite</skos:example>
            <skos:example xml:lang="en">liparite</skos:example>
            <foaf:isPrimaryTopicOf>
              <api:ItemEndpoint rdf:about="http://vocabs.ga.gov.au/cgi/sissvoc/simple-lithology/resource.rdf?uri=http://resource.geosciml.org/classifier/cgi/lithology/rhyolite">
                <foaf:primaryTopic rdf:resource="http://resource.geosciml.org/classifier/cgi/lithology/rhyolite"/>
                <rdf:type rdf:resource="http://purl.org/linked-data/api/vocab#Page"/>
                <api:extendedMetadataVersion rdf:resource="http://vocabs.ga.gov.au/cgi/sissvoc/simple-lithology/resource.rdf?_metadata=all&amp;uri=http://resource.geosciml.org/classifier/cgi/lithology/rhyolite"/>
                <api:definition rdf:resource="http://vocabs.ga.gov.au/cgi/sissvoc/simple-lithology/resource.rdf?uri=http://resource.geosciml.org/classifier/cgi/lithology/rhyolite"/>
              </api:ItemEndpoint>
            </foaf:isPrimaryTopicOf>
          </rdfs:Resource>
        </skos:member>
      </rdf:Description>
    </rdf:RDF>

Numerous other similar lithology terms exist in the CGI Simple Lithology vocabulary: 
http://resource.geosciml.org/classifier/cgi/lithology 

Also see:
http://www.cgi-iugs.org/tech_collaboration/geoscience_terminology_working_group.html

**Comment by schmar00** [comment]
Relations to other resources is an important thing - therefore links to CGI (as to INSPIRE, GEMET, GBA, etc.) are already part of keyword thesaurus v1.0.
see RDF file line 39543
```
<rdf:Description rdf:about="http://resource.geolba.ac.at/geoera_keyword/rhyolite">
	<closeMatch xmlns="http://www.w3.org/2004/02/skos/core#" rdf:resource="http://resource.geosciml.org/classifier/cgi/lithology/rhyolite"/>
</rdf:Description>
```

**Comment by nmtoken** [comment]
That's good, missed it, but shouldn't there be some exactMatch not just closeMatch relations?

**Comment by schmar00** [comment]
From the point of view of modeling approach a "keyword" isn`t exactly the same as a "scientific term" with bibliographic reference behind it. E.g. a keyword "borehole" could have a synonym "drilling" even if it is not exactly the same. Or there could be narrower expressions because "searching for this string" also implies "looking for these other narrower strings". That's why WP4 differentiates between Keyword Thesaurus and Project Vocabularies.
